module.exports = {
  status400Exceptions: [
    "Falha ao realizar login. Login ou senha estão incorretos.",
    "Falha ao realizar login. Login inexistente.",
    "Falha ao cadastrar conta. Essa conta ja existe.",
    "Falha ao cadastrar conta. Login ja existe.",
    "Falha ao cadastrar conta. Email ja existe.",
    "Falha ao cadastrar barbeiro. Barbeiro ja cadastrado.",
    "Não pode cancelar o agendamento porque falta menos de 2 horas antes do horário marcado.",
    "Você ja tem um atendimento marcado nesse horário.",
  ],
  status409Exceptions: [
    "Houve um erro ao cadastrar conta.",
    "Houve um erro ao remover conta.",
    "Falha ao obter tipos de especialidades.",
    "Falha ao obter barbeiro.",
    "Falha ao obter especialidades do barbeiro.",
    "Falha ao adicionar especialidades.",
    "Houve um erro ao remover conta.",
    "Houve um erro ao obter dados do usuário.",
    "Falha ao obter horários.",
    "Falha ao obter lista de horários.",
    "Falha ao registrar agendamento.",
    "Falha ao cancelar agendamento.",
    "Falha ao obter lista de agendamentos.",
    "FaFalha ao cadastrar barbeiro. lha ao registrar agendamento.",
  ],
};
